FROM jupyter/pyspark-notebook:spark-3.1.1

WORKDIR /app
COPY ./code .
#RUN pip3 install -r requirements.txt
RUN pip3 install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0.tar.gz 
RUN pip3 install spacy networkx dateparser matplotlib textacy pyspark numpy elasticsearch pandas requests datetime neo4j networkx 

#RUN pip --no-cache-dir install -r requirements.txt
#ENTRYPOINT ["spark-submit", "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.2", "--master", "local[*]", "streaming.py"]

